### PR TITLE
Fixes GLCameraControl flicker on Windows.

### PR DESCRIPTION
**Pull request by TaylorMutch**
Reimplemented the GLCameraButton to behave like the ExpandButton.
Todo:

- [ ] Test on macOS.

### CODE REVIEW

**Comment by TaylorMutch** [comment]
Changes here may affect #67.

**Comment by nikmolnar** [comment]
Let's hold off on this for a bit. I'm exploring implementation of these buttons as a 2D overlay in OpenGL. If that pans out, it will obviate this problem.

**Comment by TaylorMutch** [comment]
Sounds good to me! I'm also partial to the idea of moving these buttons to a different part of the UI entirely (really I'm up for any alternative).

**Comment by TaylorMutch** [comment]
Closing in anticipation of merging #81 instead, which is a better solution.

**Pull request closed without merging**
